obj-$(CONFIG_QTI_MHI_BUS)	+= mhi/
obj-$(CONFIG_QTI_QRTR)	+= qrtr/
obj-$(CONFIG_QTI_RMNET_DATA)	+= rmnet_data/
obj-$(CONFIG_QTI_USB_RMNET)	+= rmnet_usb/
obj-$(CONFIG_QTI_USB_BRIDGE)	+= usb_bridge/
obj-$(CONFIG_QTI_DIAG_CHAR)	+= diag/
obj-$(CONFIG_QTI_USB_F_DIAG)	+= usb_diag/
obj-$(CONFIG_QTI_QMI_HELPERS)	+= qmi/
